inherit_from: .rubocop_todo.yml

require:
  - rubocop-rspec
  - rubocop-rails

AllCops:
  Exclude:
    - 'vendor/**/*'
    - 'tmp/**/*'
    - '.git/**/*'
    - 'bin/*'
    - 'node_modules/**/*'
    - 'db/migrate/2019*'
    - 'db/migrate/2020*'
    - 'db/migrate/202101*'
    - 'db/migrate/202102*'

  TargetRubyVersion: 3.0
  NewCops: enable

Rails/EnvironmentVariableAccess:
  AllowReads: true # https://github.com/rubocop/rubocop-rails/pull/442#issuecomment-840458448

Naming/VariableNumber:
  EnforcedStyle: snake_case

RSpec/AnyInstance:
  Enabled: false

RSpec/ExpectInHook:
  Enabled: false

RSpec/MessageChain:
  Enabled: false

RSpec/InstanceVariable:
  Enabled: false

# Prefer allow over expect when configuring a response.
RSpec/StubbedMock:
  Enabled: false
