language: ruby
rvm:
  - 2.5.3
bundler_args: --without production:development
cache:
  - bundler
before_install:
  - gem update --system # travis-ci/travis-ci#8978
  - gem install bundler
script:
  - bundle exec rake db:migrate RAILS_ENV=test
  - bundle exec rake
