language: ruby
services:
  - postgresql
rvm:
  - 2.6.3
bundler_args: --without production:development
cache:
  ccache: true
  bundler: true
  npm: true
  yarn: true
  directories:
  - /home/travis/.rvm/
  - $HOME/libzmq
before_install:
  - cp $TRAVIS_BUILD_DIR/vendor/bitcoin-config.ini $TRAVIS_BUILD_DIR/vendor/bitcoin/test/config.ini
  - $TRAVIS_BUILD_DIR/travis-zmq.sh
  - cd $TRAVIS_BUILD_DIR/vendor/bitcoin && contrib/devtools/previous_release.sh -b -t .. v0.19.0.1
  - yarn
before_script:
  - bundle exec rake db:create RAILS_ENV=test
  - bundle exec rake db:schema:load RAILS_ENV=test
script:
  - bundle exec rake
  - npm test
  - npm run coveralls || echo "push to coveralls failed"
